export const appColors = [
  'crimson',
  'blue',
  'orange',
  'mediumseagreen',
  'cornflowerblue',
  'darkslategray',
  'darkred',
  'tomato',
  'turquoise',
  'salmon',
  'skyblue',
  'orchid',
  'mediumpurple',
  'darkkhaki',
  'dimgrey',
  'lightcoral',
  'teal',
  'sandybrown',
  'green',
  'blueviolet'
] as const
