export const appColors = [
  'lightpink',
  'lightblue',
  'orange',
  'mediumseagreen',
  'cornflowerblue',
  'gold',
  'plum',
  'tomato',
  'turquoise',
  'salmon',
  'skyblue',
  'orchid',
  'mediumpurple',
  'darkkhaki',
  'dimgrey',
  'lightcoral',
  'aquamarine',
  'sandybrown',
  'palegreen',
  'blueviolet'
] as const
